### PR TITLE
Add a readme with instructions on how to run the program.

### PR DESCRIPTION
**Pull request by dsgoers**

### CODE REVIEW

**Comment by hlbraddock** [comment]
Nice! 

I would also add steps
3.  
% mvn clean package
% <command to invoke main on this app>
4. <instructions for ftp upload>

**Comment by hlbraddock** [comment]
And sftp steps for upload?

**Comment by dsgoers** [comment]
Good idea, added.

**Comment by hlbraddock** [comment]
Great. Thanks! +1

**Pull request merged**
